<%@ Page Title="" Language="C#" MasterPageFile="~/HomePage.Master" AutoEventWireup="true" CodeBehind="GridPage.aspx.cs" Inherits="OnlineShoppingWeb.GridPage" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder" runat="server">
    <div>
        <table>
            <tr>
                <td>
                     <asp:GridView ID="ProductTable" runat="server" AutoGenerateColumns="false" DataKeyNames="ProductList" 
        OnRowUpdating="ProductTable_ListUpdate" OnRowCancelingEdit="ProductTable_ListCancelEdit" 
        OnRowEditing="ProductTable_ListEdit" OnRowDeleting="ProductTable_ListDelete"
        ShowFooter="true" AutoGenerateDeleteButton="true" AutoGenerateEditButton="true">
        <Columns>
            <asp:TemplateField HeaderText="S.No">
                <ItemTemplate>
                     <asp:Label ID="LblSerial" Text='<%# Container.DataItemIndex + 1 %>' runat="server" />
                </ItemTemplate>
                <%--<FooterTemplate>
                        <asp:LinkButton ID ="BtInsert" Text ="Insert" runat ="server" OnClick ="Insert_Click" />
                </FooterTemplate>--%>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Product Id" >
                <EditItemTemplate>  
                    <asp:TextBox ID="txtProductId" runat="server" Text='<%# Bind("ProductId") %>'/>
                </EditItemTemplate> 
                <ItemTemplate>
                    <asp:Label ID="LblId" Text='<%Bind("ProductId") %>' runat="server">
                    </asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Product Name" >
                <EditItemTemplate>  
                                <asp:TextBox ID="txtProductName" runat="server" Text='<%# Bind("ProductName") %>'></asp:TextBox>
                </EditItemTemplate> 
                <ItemTemplate>
                    <asp:Label ID="LblName" Text='<%Bind("ProductName") %>' runat="server"/>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Category ID" >
                <EditItemTemplate>  
                                <asp:TextBox ID="txtCategoryID" runat="server" Text='<%# Bind("CategoryID") %>'></asp:TextBox>
                </EditItemTemplate> 
                <ItemTemplate>
                    <asp:Label ID="LblCategoryID" Text='<%Bind("CategoryID") %>' runat="server"/>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Price" >
                <EditItemTemplate>  
                                <asp:TextBox ID="txtPrice" runat="server" Text='<%# Bind("Price") %>'></asp:TextBox>
                </EditItemTemplate> 
                <ItemTemplate>
                    <asp:Label ID="LblPrice" Text='<%Bind("Price") %>' runat="server"/>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Stocks" >
                <EditItemTemplate>  
                                <asp:TextBox ID="txtStocks" runat="server" Text='<%# Bind("Stocks") %>'></asp:TextBox>
                </EditItemTemplate> 
                <ItemTemplate>
                    <asp:Label ID="LblStocks" Text='<%Bind("Stocks") %>' runat="server"/>
                </ItemTemplate>
            </asp:TemplateField>
        </Columns>
    </asp:GridView>
                </td>
            </tr>
        </table>

    </div>
</asp:Content>
