<%@ Page Title="" Language="C#" MasterPageFile="~/HomePage.Master" AutoEventWireup="true" CodeBehind="ProductList.aspx.cs" Inherits="OnlineShoppingWeb.ProductList" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder" runat="server">
    <br />
    <br />
    <asp:GridView ID="ProductTable" runat="server" AutoGenerateColumns="false" DataKeyNames="ProductId" OnRowUpdating="ProductTable_ListUpdate"
        OnRowCancelingEdit="ProductTable_ListCancelEdit" OnRowEditing="ProductTable_ListEdit" OnRowDeleting="ProductTable_ListDelete" ShowFooter="true"
        AutoGenerateDeleteButton="true" AutoGenerateEditButton="true">
        <Columns>
            <asp:TemplateField HeaderText="S.No">
                <ItemTemplate>
                    <asp:Label ID="LblSerial" Text='<%# Container.DataItemIndex + 1 %>' runat="server" />
                </ItemTemplate>
                <FooterTemplate>
                    <asp:LinkButton ID="BtInsert" Text="Insert" runat="server" OnClick="Insert_Click" />
                </FooterTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Product Id">
                <ItemTemplate>
                    <asp:Label ID="LblId" Text='<%#Bind("ProductId") %>' runat="server">
                    </asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Product Name">
                <FooterTemplate>
                    <asp:TextBox ID="txtProductName" runat="server" Text='<%# Bind("ProductName") %>'></asp:TextBox>
                </FooterTemplate>
                <EditItemTemplate>
                    <asp:TextBox ID="txtProductNameEdit" runat="server" Text='<%# Bind("ProductName") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="LblName" Text='<%#Bind("ProductName") %>' runat="server" />
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Category ID">
                <FooterTemplate>
                    <asp:TextBox ID="txtCategoryID" runat="server" Text='<%# Bind("CategoryID") %>'/>
                </FooterTemplate>
                <EditItemTemplate>
                    <asp:TextBox ID="txtCategoryIDEdit" runat="server" Text='<%# Bind("CategoryID") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="LblCategoryID" Text='<%#Bind("CategoryID") %>' runat="server" />
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Price">
                <FooterTemplate>
                    <asp:TextBox ID="txtPrice" runat="server" Text='<%# Bind("Price") %>'></asp:TextBox>
                </FooterTemplate>
                <EditItemTemplate>
                    <asp:TextBox ID="txtPriceEdit" runat="server" Text='<%# Bind("Price") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="LblPrice" Text='<%#Bind("Price") %>' runat="server" />
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Stocks">
                <FooterTemplate>
                    <asp:TextBox ID="txtStocks" runat="server" Text='<%# Bind("Stocks") %>'></asp:TextBox>
                </FooterTemplate>
                <EditItemTemplate>
                    <asp:TextBox ID="txtStocksEdit" runat="server" Text='<%# Bind("Stocks") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="LblStocks" Text='<%#Bind("Stocks") %>' runat="server" />
                </ItemTemplate>
            </asp:TemplateField>
        </Columns>
    </asp:GridView>
</asp:Content>
